server:
  port: 8080
  servlet:
    context-path: /my-config

app:
  name: "shop"
  version: 1.2
  description: "Clothes"

api:
  url: "https://shop.ru"
  timeout: 3000
  api-key: ${API_KEY:default_secret}

