spring:
  profiles:
    active: prod

server:
  port: 8080
  servlet:
    context-path: /api

app:
  name: shop
  version: 1.0.0
  description: Clothes

api:
  url: https://shop.ru
  timeout: 8000
  api-key: ${API_KEY:default_secret}

logging:
  level:
    root: WARN
  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: refresh, info,env,health
  endpoint:
    health:
      show-details: always
